# Generated by Django 4.1.7 on 2023-03-21 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppNerilan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='formadepago',
            new_name='metododepago',
        ),
    ]
