# Generated by Django 4.1.7 on 2023-03-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNerilan', '0003_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='antiguedad',
            new_name='antiguedadMeses',
        ),
        migrations.AddField(
            model_name='empleado',
            name='recibo',
            field=models.FileField(default=12, upload_to='recibo/'),
            preserve_default=False,
        ),
    ]
