# Generated by Django 4.1.7 on 2023-03-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNerilan', '0005_articulo_alter_cliente_tienedeuda_eleccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('ver_opcion1', 'Puede ver la opción 1'), ('ver_opcion2', 'Puede ver la opción 2')],
            },
        ),
    ]
