# Generated by Django 4.1.7 on 2023-03-29 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppNerilan', '0006_tumodelo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TuModelo',
        ),
    ]
