# Generated by Django 4.1.7 on 2023-04-02 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppNerilan', '0007_delete_tumodelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleccion',
            name='comentario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eleccion',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eleccion',
            name='fecha_eleccion',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='ClienteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
