# Generated by Django 4.1.7 on 2023-04-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppNerilan', '0009_alter_cliente_nombre_delete_clienteusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='cliente',
        ),
    ]
