# Generated by Django 4.1.7 on 2023-04-05 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppNerilan', '0010_rename_nombre_cliente_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
